# Staging
- name: staging
  ip: 100.0.0.21
  cpus: 1
  mem: 2048
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
# Production
- name: production
  ip: 100.0.0.22
  cpus: 1
  mem: 2048
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
# CI-Server (Jenkins/sonarqube/jfrog)
- name: ci-server
  ip: 100.0.0.10
  cpus: 2
  mem: 4096
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
# Monitoring (Prometheus/Grafana & ELK)
- name: monitoring
  ip: 100.0.0.23
  cpus: 2
  mem: 4096
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
