# Staging
- name: staging
  ip: 100.0.0.21
  cpus: 1
  mem: 2048
  os: centos/7
  provisioner: ansible
  aliases: []
  playbook: provisioning/staging.yml
# Production
- name: production
  ip: 100.0.0.22
  cpus: 1
  mem: 2048
  os: centos/7
  provisioner: ansible
  aliases: []
  playbook: provisioning/production.yml
# CI-Server (Jenkins/sonarqube/jfrog)
- name: ci-server
  ip: 100.0.0.10
  cpus: 2
  mem: 8192
  os: centos/7
  provisioner: ansible
  aliases: []
  playbook: provisioning/ci-server.yml
# Monitoring (Prometheus/Grafana & ELK)
- name: monitoring
  ip: 100.0.0.11
  cpus: 1
  mem: 2048
  os: centos/7
  provisioner: none
  aliases: []
  playbook: provisioning/monitoring.yml
# Dev machine
- name: dev1
  ip: 100.0.0.45
  cpus: 1
  mem: 1024
  os: centos/7
  provisioner: ansible
  aliases: []
  playbook: provisioning/dev-machine.yml
# REVERSE PROXY FOR ALL THESE
- name: proxy
  ip: 100.0.0.3
  cpus: 1
  mem: 1024
  os: centos/7
  provisioner: ansible
  aliases: ["jenkins.local", "jenkins", "sonar", "sonar.local", "artifactory", "artifactory.local", "elasticsearch.local", "kibana.local", "prometheus.local"]
  playbook: provisioning/proxy.yml
