- name: Install and configure a developer machine
  become: yes
  hosts: dev1
  
  tasks:
  - name: Install git
    yum:
      name: git
      state: present
      update_cache: yes

  - name: Install vim
    yum:
      name: vim
      state: present

  - name: Install maven
    yum:
      name: maven
      state: present

  roles:
  - role: "roles/geerlingguy.java"
