- name: Install and configure the Prometheus+ELK machine
  become: yes
  hosts: monitoring

  pre_tasks:
  - name: refresh certificates
    yum:
      name: ca-certificates
      state: latest
      update_cache: yes
  
  tasks:
  - name: Install epel-release
    yum:
      name: epel-release
      state: present
      update_cache: yes


  roles:
  - role: "roles/geerlingguy.elasticsearch"
  - role: "roles/geerlingguy.kibana"
  - role: "roles/geerlingguy.logstash"
  - role: "roles/geerlingguy.node_exporter"
  - role: "roles/cloudalchemy.prometheus"
    vars:
      prometheus_targets:
        node:
        - targets:
          - monitoring:9100
          - ci-server:9100
          - staging:9100
          - production:9100
          labels:
            env: infra
        cadvisor:
        - targets:
          - ci-server:8080
          - staging:8080
          labels:
            env: docker
