- name: Install and configure the Production machine
  become: yes
  hosts: production

  pre_tasks:
  - name: refresh certificates
    yum:
      name: ca-certificates
      state: latest
      update_cache: yes

  tasks:
  - name: Install ssh key
    lineinfile:
      path: /home/vagrant/.ssh/authorized_keys
      line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0TxkzwaQ3VF39WVQLMEua6F2zaUsJiuaWZJhBxYZrquBTCWt7dDlBNQa3gB5LI/43qeyXxf0Hqios2sqqp/OVKGglOTRlvrk/3cJPCaMaZkrfW0uGJnfbIdU81Xr5YE6B6uFOZY0zXDA3gFFsKpmrVcVjRAFyHgi7nk3BbcLHoVIffnTMKKmqg7uEDSwtB5o5eoYNTFaFHWBuqQRGTSFhPIqzsvEtJZcb7JIyUY+qLWCBzVONGLLeXlbxxWAg1idOrs3gllaDViysaTyPNJeC4zB/Zh8nXAsNvaYpbAbIo28OpA5Ns9ad7mpkXiHXJpgjgbgtOmmLG0qQezrdUHHMO8BjJtntmJucyAtuZjHCymP7O9wWlZVAKpNkOX3hjXkysJhWVoI6PZkAgB3kCshYaiwCqJ4qZBYD8vRzqaU07j5WMcceyedCjGvHPVcMB+8PP1xEWXLrVGNO/WBvYmZNr3Sg0uJMbiXuxVjXuk/KwcBel5CQkKLT4LlvQcW+dg9rtw+x5P1wzhGC8nMEsHDahHZ1lWwJnH3y5R6xDHAa47ULIbl9FVNe1aOb3FdoRDXz0cVWzdoILbfewKyenFncw6Exwh36BcDF/WwG6u3UhJDR2ZrbbwZy03Npovr/I/aGSkJ/5zog8zkV+D0Ajel186hm/wQNsOj1W+49cdn71Q== vagrant@ci-server"
      state: present
      backup: yes
     register: example2out

  roles:
  - role: "roles/geerlingguy.docker"
    vars:
      docker_users: ["vagrant"]
  - role: "roles/geerlingguy.node_exporter"
  - role: "roles/ome.cadvisor"
