- name: Install and configure the Production machine
  become: yes
  hosts: production

  pre_tasks:
  - name: refresh certificates
    yum:
      name: ca-certificates
      state: latest
      update_cache: yes

  roles:
  - role: "roles/geerlingguy.docker"
    vars:
      docker_users: ["vagrant"]
  - role: "roles/geerlingguy.node_exporter"
  - role: "roles/ome.cadvisor"
