- name: Install and configure the reverse Proxy
  become: yes
  hosts: proxy

  pre_tasks:
  - name: refresh certificates
    yum:
      name: ca-certificates
      state: latest
      update_cache: yes
  
  tasks:
  - name: Install epel-release
    yum:
      name: epel-release
      state: present
      update_cache: yes

  - name: Install nginx and selinux python module
    yum:
      name:
        - nginx
        - policycoreutils-python
      state: present
      update_cache: yes

  - name: Copy nginx configuration
    copy:
      src: ./resources/nginx-reverseproxy.conf
      dest: /etc/nginx/conf.d/nginx-reverseproxy.conf
      owner: root

  - name: Disable SELinux protection for nginx
    seboolean:
      name: "httpd_can_network_connect"
      state: "1"
      persistent: true
  
  - name: Run nginx and enable it
    service:
      name: nginx
      state: restarted
      enabled: true
