- name: Install and configure the reverse Proxy
  become: yes
  hosts: proxy

  pre_tasks:
  - name: refresh certificates
    yum:
      name: ca-certificates
      state: latest
      update_cache: yes
  
  tasks:
  - name: Install epel-release
    yum:
      name: epel-release
      state: present
      update_cache: yes

  - name: Install nginx
    yum:
      name: nginx
      state: present
      update_cache: yes

  - name: Copy nginx configuration
    copy:
      src: /vagrant/provisioning/resources/nginx-reverseproxy.conf
      dest: /etc/nginx/conf.d/nginx-reverseproxy.conf
      owner: root
      remote_src: true
  
  - name: Run nginx and enable it
    service:
      name: nginx
      state: restarted
      enabled: true
